# theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
# format = "{used}"

[[block]]
block = "memory"
display_type = "memory"
# format_mem = "{Mum} MiB"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
# format = "{frequency}"
# per_core = false

[[block]]
block = "load"
interval = 1
format = "{1m}"


# [[block]]
# block = "hueshift"
# hue_shifter = "redshift"
# step = 50
# click_temp = 3500
# # icon = "weather_sun"

[[block]]
block = "net"
device = "enp6s0"
# format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
format = "{ip}{speed_up}{speed_down} {bitrate} "
interval = 5
# use_bits = false

[[block]]
block = "toggle"
text = "hd-au"
command_on='''pactl list sinks short | rg "alsa_output.+hdmi-stereo[^\s]*" -o | xargs pactl set-default-sink'''
command_off='''pactl list sinks short | rg --invert-match "alsa_output.+hdmi-stereo[^\s]*" | cut -f 2 | xargs pactl set-default-sink'''
command_state="pactl get-default-sink | rg hdmi"
interval = 3600

[[block]]
block = "toggle"
text = "lck"
command_on="xset s 600"
command_off="xset s off"
command_state='''xset q | rg "timeout:\s+[^0 ]+"'''
interval = 3600

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = false
show_fan_speed = true
show_clocks = true
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "pgrep gsimplecal || gsimplecal"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"


[[block]]
block = "sound"
max_vol = 100

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#586A6AAA"
idle_fg = "#EFECCA"
# info_bg = "#B56576"
# info_fg = "#EEF0F2"
# good_bg = "#53917E"
# good_fg = "#EEF0F2"
warning_bg = "#D62246AA"
# warning_fg = "#EEF0F2"
critical_bg = "#D62246"
# critical_fg = "#EEF0F2"
# # separator = "\ue0b2"
# separator_bg = "auto"
# separator_fg = "auto"
alternating_tint_bg = "#202000AA"
# alternating_tint_fg = "#000000"
